// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: snapshot.proto

package apbf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Snapshot struct {
	K                    uint64   `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	L                    uint64   `protobuf:"varint,2,opt,name=l,proto3" json:"l,omitempty"`
	G                    uint64   `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	R                    uint64   `protobuf:"varint,4,opt,name=r,proto3" json:"r,omitempty"`
	Base                 uint64   `protobuf:"varint,5,opt,name=base,proto3" json:"base,omitempty"`
	Count                uint64   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Buffer               []byte   `protobuf:"bytes,7,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{0}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetK() uint64 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *Snapshot) GetL() uint64 {
	if m != nil {
		return m.L
	}
	return 0
}

func (m *Snapshot) GetG() uint64 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Snapshot) GetR() uint64 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Snapshot) GetBase() uint64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *Snapshot) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Snapshot) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func init() {
	proto.RegisterType((*Snapshot)(nil), "apbf.Snapshot")
}

func init() { proto.RegisterFile("snapshot.proto", fileDescriptor_0c8aab8e59648e0b) }

var fileDescriptor_0c8aab8e59648e0b = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0x4b, 0x2c,
	0x28, 0xce, 0xc8, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x48, 0x4a,
	0x53, 0x6a, 0x61, 0xe4, 0xe2, 0x08, 0x86, 0x4a, 0x08, 0xf1, 0x70, 0x31, 0x66, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x04, 0x31, 0x66, 0x83, 0x78, 0x39, 0x12, 0x4c, 0x10, 0x5e, 0x0e, 0x88, 0x97,
	0x2e, 0xc1, 0x0c, 0xe1, 0xa5, 0x83, 0x78, 0x45, 0x12, 0x2c, 0x10, 0x5e, 0x91, 0x90, 0x10, 0x17,
	0x4b, 0x52, 0x62, 0x71, 0xaa, 0x04, 0x2b, 0x58, 0x00, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x4d, 0xce,
	0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x03, 0x0b, 0x42, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x49, 0xa5, 0x69,
	0x69, 0xa9, 0x45, 0x12, 0xec, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x4d,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x4f, 0x6d, 0xfc, 0xa5, 0x00, 0x00, 0x00,
}
